apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        image: bettingappgrad.azurecr.io/system:1.0-SNAPSHOT
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: guidesecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: bettingappgrad.azurecr.io/inventory:1.0-SNAPSHOT
        ports:
        - containerPort: 80
        env:
      imagePullSecrets:
      - name: guidesecret
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: ClusterIp
  selector:
    app: system
  ports:
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    port: 80